[[Xorg_libXScrnSaver]]
arch = "aarch64"
git-tree-sha1 = "2fc44aa5738c18b92ba444ebaeb439660371859e"
libc = "glibc"
os = "linux"

    [[Xorg_libXScrnSaver.download]]
    sha256 = "f196a33d118f201362d4546300a86371a3a8bef355248a8e183cdda749ef9415"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXScrnSaver_jll.jl/releases/download/Xorg_libXScrnSaver-v1.2.5+0/Xorg_libXScrnSaver.v1.2.5.aarch64-linux-gnu.tar.gz"
[[Xorg_libXScrnSaver]]
arch = "aarch64"
git-tree-sha1 = "1182fcfad72521631a1eea63aa23f9780285f834"
libc = "musl"
os = "linux"

    [[Xorg_libXScrnSaver.download]]
    sha256 = "13b45d1379ecf0e6187307ee1a2aa7b878668cd24d2a98f25c44ba281a279b14"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXScrnSaver_jll.jl/releases/download/Xorg_libXScrnSaver-v1.2.5+0/Xorg_libXScrnSaver.v1.2.5.aarch64-linux-musl.tar.gz"
[[Xorg_libXScrnSaver]]
arch = "aarch64"
git-tree-sha1 = "e1e45e6ed36aacbcb2a7710dddf937e953cb97b2"
os = "freebsd"

    [[Xorg_libXScrnSaver.download]]
    sha256 = "3d0be59f101524116ee70c3e7d1268a309c50dd7dbaaecc28db789ca2c8017f1"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXScrnSaver_jll.jl/releases/download/Xorg_libXScrnSaver-v1.2.5+0/Xorg_libXScrnSaver.v1.2.5.aarch64-unknown-freebsd.tar.gz"
[[Xorg_libXScrnSaver]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e9d2261a28f99ba726dd63d5a563e1aa2b13d5ce"
libc = "glibc"
os = "linux"

    [[Xorg_libXScrnSaver.download]]
    sha256 = "ea9794f29c9727daf26e0d48c6a17dd8104c3ddbcc486ba3627d4642bdc7be67"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXScrnSaver_jll.jl/releases/download/Xorg_libXScrnSaver-v1.2.5+0/Xorg_libXScrnSaver.v1.2.5.armv6l-linux-gnueabihf.tar.gz"
[[Xorg_libXScrnSaver]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9258fc86b09e0bfa8581c5924f1d65e8e02506fb"
libc = "musl"
os = "linux"

    [[Xorg_libXScrnSaver.download]]
    sha256 = "4eee1495f5be1e8d1ac16a4d82cf2e3bdada8c92e8162866905c4a524b1dfae5"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXScrnSaver_jll.jl/releases/download/Xorg_libXScrnSaver-v1.2.5+0/Xorg_libXScrnSaver.v1.2.5.armv6l-linux-musleabihf.tar.gz"
[[Xorg_libXScrnSaver]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f437d013b242217de7a6249cdc3fc58b74b8f073"
libc = "glibc"
os = "linux"

    [[Xorg_libXScrnSaver.download]]
    sha256 = "08b8b9df73afb19946c34d982f01e8d86bbb580d72bde29a122f836149cd31fb"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXScrnSaver_jll.jl/releases/download/Xorg_libXScrnSaver-v1.2.5+0/Xorg_libXScrnSaver.v1.2.5.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libXScrnSaver]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d91d9695027626e48ace20131be7a035fdda7402"
libc = "musl"
os = "linux"

    [[Xorg_libXScrnSaver.download]]
    sha256 = "69f2f37716723ff4a5cb84b47ccd9ff32ffe625e89246ba824bab373f3c5d13a"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXScrnSaver_jll.jl/releases/download/Xorg_libXScrnSaver-v1.2.5+0/Xorg_libXScrnSaver.v1.2.5.armv7l-linux-musleabihf.tar.gz"
[[Xorg_libXScrnSaver]]
arch = "i686"
git-tree-sha1 = "3c927cec1ab2badcc5180686a4283af3bb9d19a6"
libc = "glibc"
os = "linux"

    [[Xorg_libXScrnSaver.download]]
    sha256 = "32034760bbc17ec0a7d25be48df8d14c52c6f27234152a979ad2dffdb9ea8233"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXScrnSaver_jll.jl/releases/download/Xorg_libXScrnSaver-v1.2.5+0/Xorg_libXScrnSaver.v1.2.5.i686-linux-gnu.tar.gz"
[[Xorg_libXScrnSaver]]
arch = "i686"
git-tree-sha1 = "0eef4ce7160cd3abd60d0a07f481f3e738b4c5f0"
libc = "musl"
os = "linux"

    [[Xorg_libXScrnSaver.download]]
    sha256 = "69e99bcbfaa0cb6c14d65426535249f65c50d88452c15c66ca0054860c0d4ee8"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXScrnSaver_jll.jl/releases/download/Xorg_libXScrnSaver-v1.2.5+0/Xorg_libXScrnSaver.v1.2.5.i686-linux-musl.tar.gz"
[[Xorg_libXScrnSaver]]
arch = "powerpc64le"
git-tree-sha1 = "3f642210a898561b8527064e5bcb8a0f89b1d88c"
libc = "glibc"
os = "linux"

    [[Xorg_libXScrnSaver.download]]
    sha256 = "349c3f1cb2c9605551886a6d898f4c1b94aa55663ae344260d6b2666033d7101"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXScrnSaver_jll.jl/releases/download/Xorg_libXScrnSaver-v1.2.5+0/Xorg_libXScrnSaver.v1.2.5.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libXScrnSaver]]
arch = "riscv64"
git-tree-sha1 = "093ab1a5c3d52be1c4146dfc15f6bd9e0f00a461"
libc = "glibc"
os = "linux"

    [[Xorg_libXScrnSaver.download]]
    sha256 = "de0b1f2035a8749721b113a16126950a5469eb13195130dfb0388f56401ce1c5"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXScrnSaver_jll.jl/releases/download/Xorg_libXScrnSaver-v1.2.5+0/Xorg_libXScrnSaver.v1.2.5.riscv64-linux-gnu.tar.gz"
[[Xorg_libXScrnSaver]]
arch = "x86_64"
git-tree-sha1 = "e9ef8ebe063933b05769809d85a33deb7450cd34"
libc = "glibc"
os = "linux"

    [[Xorg_libXScrnSaver.download]]
    sha256 = "3252478369e393bca84089ca5d85b8e8097403d52fb19275e234994864dce939"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXScrnSaver_jll.jl/releases/download/Xorg_libXScrnSaver-v1.2.5+0/Xorg_libXScrnSaver.v1.2.5.x86_64-linux-gnu.tar.gz"
[[Xorg_libXScrnSaver]]
arch = "x86_64"
git-tree-sha1 = "2642fa9b71a817537f5158a745b234fe8bcfc077"
libc = "musl"
os = "linux"

    [[Xorg_libXScrnSaver.download]]
    sha256 = "625765968735a73e320f8f1e9eb944f80c5be458464a7430ba8af1c111a026c0"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXScrnSaver_jll.jl/releases/download/Xorg_libXScrnSaver-v1.2.5+0/Xorg_libXScrnSaver.v1.2.5.x86_64-linux-musl.tar.gz"
[[Xorg_libXScrnSaver]]
arch = "x86_64"
git-tree-sha1 = "75d66d8bad249e03c06d944fab3ac9da3a0e782b"
os = "freebsd"

    [[Xorg_libXScrnSaver.download]]
    sha256 = "b7b80aadba65a9b3822003c741e1e0d106615469631f691f56eb3a4724db354c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXScrnSaver_jll.jl/releases/download/Xorg_libXScrnSaver-v1.2.5+0/Xorg_libXScrnSaver.v1.2.5.x86_64-unknown-freebsd.tar.gz"
