# Autogenerated wrapper script for Xorg_libXScrnSaver_jll for aarch64-linux-gnu
export libXScrnSaver

using Xorg_libXext_jll
JLLWrappers.@generate_wrapper_header("Xorg_libXScrnSaver")
JLLWrappers.@declare_library_product(libXScrnSaver, "libXss.so.1")
function __init__()
    JLLWrappers.@generate_init_header(Xorg_libXext_jll)
    JLLWrappers.@init_library_product(
        libXScrnSaver,
        "lib/libXss.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
